### ISSUE TITLE
Missing test

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/fault-injection-maestro#5]
It would be nice with a test, such that I can try and change the maestro2 version and verify that the newest version works.

**Comment by gitting-around** [comment]
I will create a new one for that, but it will be based on the watertank controller fmu. That should work right?

**Comment by gitting-around** [comment]
Have a look at: faultinject-bundle/src/test/java/org/intocps/maestro/faultinject/maestroTest.java, and see if it's enough for your purpose.

**Comment by CThuleHansen** [comment]
Thank you. It tests the basic integration of the tools.
It might be, that we will need something in the future that needs to verify accurate simulation, i.e. accurate results.
If you find the integration to be insufficiently reliable in the future, then you can add more...

**Comment by gitting-around** [comment]
I will take care of this when I am back, as I do believe we should have some tests to verify the correctness. So I am leaving this open for now.

**Comment by gitting-around** [comment]
I created a correctness test, which it is good enough for now, but I am thinking, we can maybe create a test suite with possible xml files, and gt data, for a more thorough testing. We can modify the matlab script I created to produce different gt truth data as needed. Btw the correct test only works for outputs. For inputs, it is not possible to log through fmi interface the injected values. So we'd have to think about that. I will open a discussion on this, and close this thread, since we have the missing test.
